### ISSUE TITLE
setLimit doesn't work on fetchAll() 

### ISSUE THREAD

**Issue by litan1106** [thephpleague/csv#135] opened 2015-11-16 21:32 UTC
// Create csv reader object
        $reader = Reader::createFromPath($csvPath);
        $reader->setFlags(SplFileObject::READ_AHEAD | SplFileObject::SKIP_EMPTY);
        // Count the rows
        $count = $reader->each(function () {
            return true;
        });

        $data = $reader->setOffset(11)->setLimit(10)->fetchAll();

I was getting all the results from the csv with setLimit(10)

**Comment by nyamsprod** [comment] 2015-11-17 10:35
Hi @litan1106 
To understand your problem I need more informations:

- your OS
- your PHP version
- your League/csv version
- what you were expecting, and what you did get (ie what was the value of `$count` for instance) 
and other informations that could help me understand your problem. With the current info I am unable to reproduce your bug if it is a bug to begin with ? If you look at the examples folder there's a script that just use the same code you gave me and works as intended

**Comment by litan1106** [comment] 2015-11-17 16:24
OS: Ubuntu 14.04
PHP: 5.5.9
Leagure/csv: 7.20

$csvPath is the path of the csv file which it has 20 rows of data. $count was used to get the number of rows.

**Comment by nyamsprod** [comment] 2015-11-18 08:43
@litan1106 did you try to set correctly your CSV file controls (delimiter, enclosure, escape) characters to match your CSV file ? Please check the documentation for that

**Comment by nyamsprod** [comment] 2015-11-24 12:59
@litan1106 did you fix your problem ? If so can you close this issue please.

**Closed** 2015-11-26 11:40 UTC
Labels: question
