### ISSUE TITLE
setDelimiter has no effect on output 

### ISSUE THREAD

**Issue by alperyazgan** [thephpleague/csv#244] opened 2017-08-21 13:16 UTC
## Issue summary
In the following simple writer setting, CSV insistingly creating file with delimiter comma (default)

...
      {
        $writer = Writer::createFromPath($tmpFile, 'w+');
        RFC4180Field::addTo($writer);
//        $writer->setEnclosure('"');
        **$writer->setDelimiter('|');
        echo $writer->getDelimiter(); // Prints "|" correctly**
//        $writer->setEscape('\\');
        $writer->setNewline("\r\n");
        $writer->insertOne($this->getColumnListing());
        $this->query()->orderBy($this->getKeyName())->chunk($this->getExportChunkSize(), function ($items) use ($writer) {
          $items->each(function ($item) use ($writer) {
            $writer->insertOne($item->getAttributes());
          });
        });
      }
...

### System informations

PHP 7.1.8-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Aug  3 2017 18:37:39) ( NTS )

CSV version from composer.json 
    "extra": {
        "branch-alias": {
            "dev-master": "9.x-dev"
        }
    }

**Comment by nyamsprod** [comment] 2017-08-21 13:46
@alperyazgan thanks for reporting this bug a fix is on its way 👍

**Comment by alperyazgan** [comment] 2017-08-21 14:02
And the enclosure has the same problem ...

**Comment by nyamsprod** [comment] 2017-08-21 14:05
Yes all CSV controls are fixed in the patch . It is taking a bit of time because github has some issues right now. I'll put it on prod ASAP.

**Closed** 2017-08-21 14:44 UTC
Labels: bug

**Comment by nyamsprod** [comment] 2017-08-22 06:33
version 9.0.1 is released. 

@alperyazgan  Of note, in your example the RFC4180Field filter may not work as intended as you are setting your delimiter **after** adding the filter. You should add the filter once you have sets your CSV controls otherwise the results may be unexpected.
