### ISSUE TITLE
Problem with json in csv rows

### ISSUE THREAD

**Issue by rbruhn** [thephpleague/csv#219] opened 2017-03-07 22:08 UTC
When dealing with a JSON string inside a cell during import, the escaped characters and quotes seem to be breaking the row into more columns that really exist. Is there a way around this?

For example, here is a JSON string inside the CSV row cell:
```
[{"task":"T12","value":[{"select_label":"County","option":true,"value":"cf8cff3800c4a","label":"Escambia"}]},{"task":"T5","task_label":null,"value":[{"task":"T2","value":"Ajuga reptans","task_label":"Scientific Name"},{"task":"T3","value":"Near Pensacola. 199 Overlook Dr.  N 30.50'14'16\" W 87.24'82'95\".","task_label":"Location"},{"task":"T4","value":"Cultivated. Flws bluish-puple. Soil sandy.","task_label":"Habitat \u0026 Description"}]},{"task":"T11","task_label":null,"value":[{"task":"T6","value":"James R. Burkhalter","task_label":"Collected By"},{"task":"T7","value":"3736","task_label":"Collector Number"},{"task":"T8","value":[{"select_label":"Month","option":true,"value":4,"label":"4 - April"}]},{"task":"T9","value":[{"select_label":"Day","option":true,"value":17,"label":"17"}]},{"task":"T10","value":[{"select_label":"Year","option":true,"value":1976,"label":"1976"}]}]}]
```

In the part: "Near Pensacola. 199 Overlook Dr.  N 30.50'14'16\" W 87.24'82'95\".",
The results get parsed as different columns and I end up with this array

```
[10] => [{"task":"T12","value":[{"select_label":"County","option":true,"value":"cf8cff3800c4a","label":"Escambia"}]},{"task":"T5","task_label":null,"value":[{"task":"T2","value":"Ajuga reptans","task_label":"Scientific Name"},{"task":"T3","value":"Near Pensacola. 199 Overlook Dr.  N 30.50'14'16\" W 87.24'82'95\"".""
    [11] => task_label"":""Location""}
    [12] => {""task"":""T4""
    [13] => value"":""Cultivated. Flws bluish-puple. Soil sandy.""
    [14] => task_label"":""Habitat \u0026 Description""}]}
    [15] => {""task"":""T11""
    [16] => task_label"":null
    [17] => value"":[{""task"":""T6""
    [18] => value"":""James R. Burkhalter""
    [19] => task_label"":""Collected By""}
    [20] => {""task"":""T7""
    [21] => value"":""3736""
    [22] => task_label"":""Collector Number""}
    [23] => {""task"":""T8""
    [24] => value"":[{""select_label"":""Month""
    [25] => option"":true
    [26] => value"":4
    [27] => label"":""4 - April""}]}
    [28] => {""task"":""T9""
    [29] => value"":[{""select_label"":""Day""
    [30] => option"":true
    [31] => value"":17
    [32] => label"":""17""}]}
    [33] => {""task"":""T10""
    [34] => value"":[{""select_label"":""Year""
    [35] => option"":true
    [36] => value"":1976
    [37] => label"":""1976""}]}]}]"
```

**Comment by nyamsprod** [comment] 2017-03-08 07:47
@rbruhn Having Json into CSV records is a recipe for disaster :) . Anyway how is you Reader object configure ? Did you change the escape character ? The problem may be raised by that. IMHO this is not a bug.

**Comment by rbruhn** [comment] 2017-03-08 12:28
Hi.... no it's not a bug... definitely just a question.. lol

I've been using the reader set up like this for ordinary csv files:
```
$this->reader = Reader::createFromPath($file);
$this->reader->setDelimiter(',');
$this->reader->setEnclosure('"');
$this->reader->setEscape('\\');
```
I actually added the setEscape in an attempt to get around this issue.
The CSV file has other regular columns and data. There are just a couple columns that have the JSON strings. They are exported that way from an API I'm dealing with.

Any suggestions?

**Comment by nyamsprod** [comment] 2017-03-08 12:40
I believe there's a conflict between the CSV characters control and Json characters controls for instance the default CSV controls are all used and have meaning in JSON specification unless your CSV uses original control characters you are bound to have so type of mismatch IMHO this is because the CSV was badly produced to begin with. So there's not much to do to work around this

**Comment by rbruhn** [comment] 2017-03-08 12:49
So there isn't a way to strip the slashes or anything while reading the data? I did try using a function to do that while using "fetch" but it didn't seem to do anything.

**Comment by nyamsprod** [comment] 2017-03-08 13:00
you could use [the stream filters](http://csv.thephpleague.com/8.0/filtering/) but I won't guarantee the result. I'll close this as this is not a issue more a general question on how to parse a specific content for a specific CSV.

**Closed by nyamsprod** 2017-03-08 13:00 UTC
Labels: question

**Comment by rbruhn** [comment] 2017-03-08 15:02
Just to update in case someone stops by.... using double quote '"' as the escape character resolved my issue.

**Comment by nyamsprod** [comment] 2017-03-08 16:35
> . using double quote '"' as the escape character resolved my issue.
As I thought it was a problem of finding/choosing the correct character controls 👍
