### ISSUE TITLE
Read the number 0 at the beginning of a data in a cell from excel to csv

### ISSUE THREAD

**Issue by adalgdev** [thephpleague/csv#388] opened 2020-06-03 13:54 UTC
Version: league/csv 9.0

Hello, I am converting an excel file to csv, in one of the excel cells I have the data "010101", when obtaining the data with csv it reads "10101", ignores the initial 0

How would I not ignore this initial 0?

**Comment by nyamsprod** [comment] 2020-06-03 14:20
@adal6a thanks for using the library, could you provide a simple reproducible script to better be able to investigate and maybe patch the issue if the issue is from the package.

**Comment by adal6a** [comment] 2020-06-03 15:00
Sorry, wrong issue. My bad. Close this. Many thanks!

**Closed as completed** 2020-06-03 16:15 UTC
Labels: question, version 9.0
