### ISSUE TITLE
League\Csv\Writer - Invalid CSV 

### ISSUE THREAD

**Issue by tom-d-77** [thephpleague/csv#307] opened 2018-08-28 15:55 UTC
## Issue summary

A string with a doubled backslash at the end, leads to an invalid CSV file.
It looks like that in the CSV File:
```
"a text string \\"", "..."
```

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version | 9.1.4  |
| PHP/HHVM version | PHP 7.2 |
| OS Platform | Debian GNU/Linux 9 |

## Standalone code, or other way to reproduce the problem
Code not tested, just written to make it more easy to understand the problem:
```
$csvWriter = Writer::createFromPath('/tmp/file.csv', 'a+');
$csvWriter->setNewline("\r\n"); //RFC4180 Line feed
RFC4180Field::addTo($csvWriter);
$line=['a text string \\','...'];
$csvWriter->insertOne($line);
```

### Expected result
```
"a text string \\", "..."
```

### Actual result
```
"a text string \\"", "..."
```

**Comment by nyamsprod** [comment] 2018-09-03 09:01
@tom-d-77 thanks for submitting your bug report indeed I was able to reproduce the bug.

After some digging I found the source of the issue but resolving it won't be as simple as I thought. The main issue is that PHP fputcsv is broken beyond repair and can never generate a valid RFC4180 compliant CSV. My patch works in 80% of cases but not in 100%. So I was wondering if it woudn't be much simpler to just add a switch parameter to the Writer class so that if someone wants a true RFC4180 compliant CSV the engine would not use fputcsv at all. 

I've been toying around that concept lately If I can come up with a decent implementation then it will land on the next minor release as I won't break any existing code. 

If that solution is ok with you then the question becomes what to do with the RFC4180Field class ? Well I would deprecate the class and issue a warning in the documentation ? Thoughts ?

**Comment by nyamsprod** [comment] 2018-09-03 11:53
Seems that `fgetcsv` does not suffer from the same issue so I will only patch the `Writer` class as only `fputcsv` is broken. 

I will have to double check this but If this is true then my patch will need some ironing (adding the appropriate tests) but is aleady done. when my PR is ready I'll let you know so that you could test it with your own data that way I'll be sure I've done it correctly or maybe you'll find other subtle bugs I haven't thought about 👍

Of course this will be done/finished when I have some spare times 😢

**Comment by nyamsprod** [comment] 2018-09-07 06:56
@tom-d-77 I've toying with a local dev that fix this issue but before submitting a PR I'd like your opinion on 2 possible implemetations

### Using a dedicated setter/getter method

```php
<?php

use League\Csv\Writer;

$writer = Writer::createFromString('');
$writer->getWritingMode(); //returns Writer::MODE_PHP 
$writer->insertOne($arr); //the record is added using fputcsv
$writer->setWritingMode(Writer::MODE_RFC4180); //the new RFC4180 compliant writing mode
$writer->insertAll([$arr]); //the records are added using RFC4180 rules
```

### Using an optional argument on the insertXXX methods

```php
<?php

use League\Csv\Writer;

$writer = Writer::createFromString('');
$writer->insertOne($arr, Writer::MODE_PHP);  //the record is added using fputcsv
$writer->insertAll([$arr], Writer::MODE_RFC4180); //the records are added using RFC4180 rules
```

In both implementations, if no mode is set on the `insertXXX` methods `Writer::MODE_PHP` will be used to avoid BC break.

I'm leaning towards the second solution. Thoughts and comments ?

**Comment by tom-d-77** [comment] 2018-09-07 07:18
@nyamsprod : Sounds like a question of taste. I also would go with the secound solution, because it is less code. In my opinion there should not be to much parameters in methods - but with 2 parameters it is not to much.

But i only have seen the writing part of the library, if in general the first solution is already implemented more often, i would stay with that one.

Hope this helps a little to get a decision.

**Comment by nyamsprod** [comment] 2018-09-07 08:37
@tom-d-77 even thought most of the other setters uses the setter/getter option I believe I want to make a exception for that rule here as choosing the right engine is important and the dev should really be in control of what he wants to do. The second option forces the developer to choose wisely which is a good thing IMHO.

**Comment by tom-d-77** [comment] 2018-09-07 11:14
@nyamsprod I think you are right - the developer should know which "writer mode" is used. One more thought about it: If the second parameter has a default value, developers tend to use the default value (this is also true for me). So it may be a good decision, to set no default value to it, and throw a self explaning Error if it is not set.

**Comment by nyamsprod** [comment] 2018-09-07 11:19
I can do that as it would be BC break .. the parameter needs to be optional ... but should be required in the next major release it's the only tradeoff I see

**Comment by tom-d-77** [comment] 2018-09-07 11:40
@nyamsprod It was just a additional thought from me - i think your solution is valid in terms of a coding view.

**Comment by theodorejb** [comment] 2018-09-07 20:43
I ran into this exact same issue when trying to insert arbitrary text from a database, where some of the rows contain backslashed double quotes, commas, and newlines. Here's a code example:

```php
$csv = Writer::createFromFileObject(new SplTempFileObject());

$exampleText = <<<'EOD'
"Some text with \"backslashed\" double quotes"
Another line with "double" quotes, and a comma
EOD;

$rows = [
    ['a' => 'row 1', 'b' => 'column b'],
    ['a' => $exampleText, 'b' => 'row 2, column b'],
    ['a' => 'row 3', 'b' => 'column b'],
];

$csv->insertAll($rows);
$csv->output('escape_bug.csv');
```

When I open the CSV in Excel, it's completely broken:

![bug screenshot](https://user-images.githubusercontent.com/3053271/45241204-0bb27380-b2b1-11e8-9fc1-9ea81c6b00d2.PNG)

The double quotes are messed up, the newline created a new row, and the comma split the text into another column!

**Actual CSV contents**
```
"row 1","column b"
"""Some text with \"backslashed\" double quotes""
Another line with ""double"" quotes, and a comma","row 2, column b"
"row 3","column b"
```

**Expected CSV contents**
```
"row 1","column b"
"""Some text with \""backslashed\"" double quotes""
Another line with ""double"" quotes, and a comma","row 2, column b"
"row 3","column b"
```

I dug into the code for the `Writer` class and traced the issue back to the `fputcsv` PHP function, which takes an `$escape_char` argument defaulting to a backslash. Apparently any enclosure characters (double quotes) preceded by the escape character aren't escaped.

It turns out there is a thread on PHP internals about the issue here: https://externals.io/message/100729. The issue could be fixed in PHP by allowing a blank string to be passed to `fputcsv` for the escape character.

I was able to work around the bug by adding the following line before the call to `$csv->insertAll`:

```php
$csv->setEscape("\0");
```

Perhaps this library could also work around the issue by simply changing the default escape character to a null byte.

**Comment by nyamsprod** [comment] 2018-09-08 07:37
@theodorejb thanks for the input. When I say that

> After some digging I found the source of the issue but resolving it won't be as simple as I thought. The main issue is that PHP fputcsv is broken beyond repair and can never generate a valid RFC4180 compliant CSV.

It's because I did the same research as yours but we differ on the solution. I can not change the default settings of the lib otherwise:

- it is a major BC break so change to null byte is not a solution.
- In addition, changing to the null byte is essentially a hack what happens if you CSV document contains such character ? 

Bottom line, I've submitted a PR #309 which fix this issue and also allow broader support for RFC4180 in the library. The only downside is deprecating RFC4180Field filter and for those using it we will update the documentation and provide guidance between upgrading to the new release OR changing the espace delimilter to the null bytes otherwise if possible.

**Comment by theodorejb** [comment] 2018-09-09 14:36
@nyamsprod You're right that using a null byte as the default escape character would be a BC break, and it's somewhat of a hack that may not work in every situation.

I'm not entirely convinced that adding a new writing mode parameter is the best solution, however. It's still possible that the issue could be fixed in PHP by allowing a blank string to be set as the escape character. In the meantime before PHP allows this, perhaps this library could special-case calling `setEscape('')`, which would switch to a writing mode that doesn't use `fputcsv`. In the next major version of League/Csv, this could be the default. Then if PHP eventually supports a blank string as the escape character, the separate writing mode could be removed.

Are there any other important differences in the RFC4180 writing mode other than ignoring the escape character? If so, I'm concerned that it might be a bigger BC break than just allowing a blank escape character but keeping the rest of the `fputcsv` behavior. Also, how does the new writing mode perform compared to the native PHP function?

**Comment by nyamsprod** [comment] 2018-09-10 07:07
@theodorejb the following PR #309 contains the fix TL;DR it falls back to using `fwrite` instead of `fputcsv`.

> It's still possible that the issue could be fixed in PHP by allowing a blank string to be set as the escape character. In the meantime before PHP allows this, perhaps this library could special-case calling setEscape(''), which would switch to a writing mode that doesn't use fputcsv.

Indeed if  the upstream code in `fputcsv` was patch I would longer need the optional parameter. But since I can not 100% guarantee that this is how the patch will land (using an empty string) I'd rather not rely on a fix which has not yet land, what if the patch uses `null` or `false` instead of the empty string ?

> I'm not entirely convinced that adding a new writing mode parameter is the best solution, however. 

The issue is not with how the patch works but how it is triggered. Should it be triggered by a special input for the escape character **OR** should it be triggered by a optional argument on the insertXXX methods.

IMO using an optional argument is the best approach for the following reason **If** PHP was to fix the escape parameter bug

1. v9.2.0 introduced the `Writer::MODE_RFC4180` relying on `fwrite` (see #309);
2. PHP patchs lands on `fputcsv`;
3. a patch release for `League\Csv` is released which switch internally to `fputcsv` on all modes but still uses `fwrite` for legacy PHP version;
4. the next major release drops the `Writer::MODE_RFC4180` constant and just relies on `fputcsv` behavior;

This is clean simple and reliable. On the other hand if we use the "escape" parameter switch and the PHP patch is done differently (let's hope not 😄 ) then we will have to directly release a v10 because of potential bugs. Not to mention that nothing is said for `fgetcsv` will it be patch too to ignore the escape parameter using the same empty string 🤔 

I've seen your post on the PHP internal mailing list 👍  . Let's hope this boost the release of a patch quickly!!

> Also, how does the new writing mode perform compared to the native PHP function?

I suppose that benchmark using `fwrite` decrease insertion speed, but it should depend on the record content length 🤔 You can benchmark the PR to see the difference.

**Comment by nyamsprod** [comment] 2018-09-10 07:57
> Are there any other important differences in the RFC4180 writing mode other than ignoring the escape character? 
yes there's one `fputcsv` adds enclosures in presence of the white spaces in a record field, RFC4180 does not.

**Comment by theodorejb** [comment] 2018-09-13 13:49
There is now a pull request to fix this in PHP: https://github.com/php/php-src/pull/3515.

**Comment by nyamsprod** [comment] 2018-09-13 14:44
@theodorejb @tom-d-77 should we wait for the patch to land ? 

If it lands for PHP7.2 and PHP7.1  we will be able to get rid of the flag all together and only fallback to my implementation for version which do not support the empty string. (ie.. this code would never be called in PHP7.3+ for instance)
  
This would be IMO better because it would be transparent for the end user and provide polyfill for PHP version that do not support the empty string while taking advantage of the patch when possible.

**Comment by nyamsprod** [comment] 2018-09-13 17:37
I've updated the patch to get rid of the flag... But I also saw the response on the internals about the patch landing in min. 1 year with PHP 7.4 ... Currently the patch works but I'm not sure about the fgetcsv patch which just replace the escape character with the null byte ... Any suggestions?

**Comment by theodorejb** [comment] 2018-09-13 18:53
@nyamsprod Indeed, it sounds like the PHP patch won't land until 7.4, so a polyfill will be needed for previous versions.

I'm not sure about the `fgetcsv` approach, either. I don't really like the inconsistency it creates between reading and writing. Conceivably someone could write a CSV containing a null byte before the enclosure character, and then not be able to read it back properly. I feel that it would be better to either use a custom RFC4180-compliant reader, or replace an empty string with a null byte when both reading and writing with the native PHP functions.

Personally I think the latter approach would be fine in practice, since needing to read/write a null byte followed by a double quote seems extremely unlikely compared to reading/writing backslashed quotes.

If a custom writer is used, it also seems like it should match PHP's behavior of always surrounding fields with the enclosure character, so that this behavior won't change when upgrading to PHP 7.4.

**Comment by nyamsprod** [comment] 2018-09-13 19:01
@theodorejb patching the PR so that it escape "like" fputcsv patched is easy ... patching fgetcsv is another daunting task as it means it means creating a equivalent of fgetcsv in full userland PHP minus the escape bug... I'll see what can be done I don't like having to use the null byte hack

**Closed** 2018-09-21 11:28 UTC
Labels: bug, version 9.0
